<#
	.SYNOPSIS
		A brief description of the Controller-Sync-PKI.ps1 file.
	
	.DESCRIPTION
		A description of the file.
	
	.NOTES
		===========================================================================
		Created on:   	10/16/2017 3:27 PM
		Created by:   	Eden Nelson
		Organization: 	Cascade Technology Alliance
		Filename:     	Controller-Sync-PKI.ps1
		===========================================================================
#>
[CmdletBinding()]
param ()

$Script = $PSScriptRoot, '\','Sync-PKI.ps1' -join ''
$SourceForestName = ''
$TargetForestName = ''
$SourceDC = ''
$TargetDC = ''
$EnrollmentServicesCAs = @('')


foreach ($ESCA in $EnrollmentServicesCAs) { & $Script -SourceForestName $SourceForestName -TargetForestName $TargetForestName -SourceDC $SourceDC -TargetDC $TargetDC -ObjectType ES -ObjectCN $ESCA -Force }
& $Script -SourceForestName $SourceForestName -TargetForestName $TargetForestName -SourceDC $SourceDC -TargetDC $TargetDC -ObjectType Template -Force
& $Script -SourceForestName $SourceForestName -TargetForestName $TargetForestName -SourceDC $SourceDC -TargetDC $TargetDC -ObjectType OID
& $Script -SourceForestName $SourceForestName -TargetForestName $TargetForestName -SourceDC $SourceDC -TargetDC $TargetDC -ObjectType CA -Force
& $Script -SourceForestName $SourceForestName -TargetForestName $TargetForestName -SourceDC $SourceDC -TargetDC $TargetDC -ObjectType AIA -Force
& $Script -SourceForestName $SourceForestName -TargetForestName $TargetForestName -SourceDC $SourceDC -TargetDC $TargetDC -ObjectType NTAuth


# SIG # Begin signature block
# MIIQrgYJKoZIhvcNAQcCoIIQnzCCEJsCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUKqpRxH8vV0G9Fx8l03LSczBO
# 9T+gggvFMIIDBjCCAe6gAwIBAgIQL5tLI0kB95tC0nRJzV7uKjANBgkqhkiG9w0B
# AQUFADAWMRQwEgYDVQQDDAtFZGVuIE5lbHNvbjAeFw0xNzA5MDgyMjI2NTFaFw0z
# NzA5MDgyMjM2NTFaMBYxFDASBgNVBAMMC0VkZW4gTmVsc29uMIIBIjANBgkqhkiG
# 9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt5TChlY9pEZX/3fWVpiaKiwxvoapE4Wkvkxf
# Loj8LJxZCBJI4yWjKCyFfuZpNTkL2cR2o7S4Ikp1VxJAlHa0moH27A4Cd6WDxAPF
# ksfyENY+aFpfZSMCLql8kQg9bzMDxyW+5Lr4r2tOX3Mx03HeCLo9l3ax3GnFJ7Ur
# FEMRFviaZMxDlFT4cUmHQfL2WaFviP6bfRT3+jLs3KJWyuEVgrsgg4fZAEiTo/nu
# C2RdfT00gsqVTzrg1FyPdnE43MTcojHEiRJ14GRRFEU/CX8PntGKvUf+qAlp2GYD
# Bg/YmBEJLtFxvCo1Vja7oDubKncPPWUKmA85WXtDUsHE5YohkQIDAQABo1AwTjAO
# BgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMB0G
# A1UdDgQWBBQQmjQ9M/4E7vwm7Jt1MUCG4f43uzANBgkqhkiG9w0BAQUFAAOCAQEA
# CHkEawdt83WaQ8pqAxOdhjdr/TeVLt3IJFM/ZO/PJ9y37kJ4QXQ0hl4tmYVF9pF8
# mrPxdLRNLhGMVm+jQ8APKmAUpewFi/oRANppG2uw496eikcipB7IjwGNAUru4Wcq
# WfKAtfWNrl2HFEMpnyeI4NrGZKXxC+CTOV102SqVq2O2xiKrvFSR+NI9xCYNXXBt
# ErEw7cqGMaHPdtc0TM7coGHvbS8muoJdM8tULayji7vkPKR7D/HXEnrLe0DS/MRG
# HRPdqgGuyz8M8IVUlNevC6GEYruuBQ/D/NGThwETeVNyakIw6rMeRSXmPV3RQ17S
# k1OeaULzyA/Vo5+g9jC6NzCCBBQwggL8oAMCAQICCwQAAAAAAS9O4VLXMA0GCSqG
# SIb3DQEBBQUAMFcxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52
# LXNhMRAwDgYDVQQLEwdSb290IENBMRswGQYDVQQDExJHbG9iYWxTaWduIFJvb3Qg
# Q0EwHhcNMTEwNDEzMTAwMDAwWhcNMjgwMTI4MTIwMDAwWjBSMQswCQYDVQQGEwJC
# RTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEoMCYGA1UEAxMfR2xvYmFsU2ln
# biBUaW1lc3RhbXBpbmcgQ0EgLSBHMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
# AQoCggEBAJTvZfi1V5+gUw00BusJH7dHGGrL8Fvk/yelNNH3iRq/nrHNEkFuZtSB
# oIWLZFpGL5mgjXex4rxc3SLXamfQu+jKdN6LTw2wUuWQW+tHDvHnn5wLkGU+F5Yw
# RXJtOaEXNsq5oIwbTwgZ9oExrWEWpGLmtECew/z7lfb7tS6VgZjg78Xr2AJZeHf3
# quNSa1CRKcX8982TZdJgYSLyBvsy3RZR+g79ijDwFwmnu/MErquQ52zfeqn078Ri
# J19vmW04dKoRi9rfxxRM6YWy7MJ9SiaP51a6puDPklOAdPQD7GiyYLyEIACDG6Hu
# tHQFwSmOYtBHsfrwU8wY+S47+XB+tCUCAwEAAaOB5TCB4jAOBgNVHQ8BAf8EBAMC
# AQYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQURtg+/9zjvv+D5vSFm7Dd
# atYUqcEwRwYDVR0gBEAwPjA8BgRVHSAAMDQwMgYIKwYBBQUHAgEWJmh0dHBzOi8v
# d3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMDMGA1UdHwQsMCowKKAmoCSG
# Imh0dHA6Ly9jcmwuZ2xvYmFsc2lnbi5uZXQvcm9vdC5jcmwwHwYDVR0jBBgwFoAU
# YHtmGkUNl8qJUC99BM00qP/8/UswDQYJKoZIhvcNAQEFBQADggEBAE5eVpAeRrTZ
# STHzuxc5KBvCFt39QdwJBQSbb7KimtaZLkCZAFW16j+lIHbThjTUF8xVOseC7u+o
# urzYBp8VUN/NFntSOgLXGRr9r/B4XOBLxRjfOiQe2qy4qVgEAgcw27ASXv4xvvAE
# SPTwcPg6XlaDzz37Dbz0xe2XnbnU26UnhOM4m4unNYZEIKQ7baRqC6GD/Sjr2u8o
# 9syIXfsKOwCr4CHr4i81bA+ONEWX66L3mTM1fsuairtFTec/n8LZivplsm7HfmX/
# 6JLhLDGi97AnNkiPJm877k12H3nD5X+WNbwtDswBsI5//1GAgKeS1LNERmSMh08W
# YwcxS2Ow3/MwggSfMIIDh6ADAgECAhIRIdaZp2SXPvH4Qn7pGcxTQRQwDQYJKoZI
# hvcNAQEFBQAwUjELMAkGA1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYt
# c2ExKDAmBgNVBAMTH0dsb2JhbFNpZ24gVGltZXN0YW1waW5nIENBIC0gRzIwHhcN
# MTYwNTI0MDAwMDAwWhcNMjcwNjI0MDAwMDAwWjBgMQswCQYDVQQGEwJTRzEfMB0G
# A1UEChMWR01PIEdsb2JhbFNpZ24gUHRlIEx0ZDEwMC4GA1UEAxMnR2xvYmFsU2ln
# biBUU0EgZm9yIE1TIEF1dGhlbnRpY29kZSAtIEcyMIIBIjANBgkqhkiG9w0BAQEF
# AAOCAQ8AMIIBCgKCAQEAsBeuotO2BDBWHlgPse1VpNZUy9j2czrsXV6rJf02pfqE
# w2FAxUa1WVI7QqIuXxNiEKlb5nPWkiWxfSPjBrOHOg5D8NcAiVOiETFSKG5dQHI8
# 8gl3p0mSl9RskKB2p/243LOd8gdgLE9YmABr0xVU4Prd/4AsXximmP/Uq+yhRVmy
# Lm9iXeDZGayLV5yoJivZF6UQ0kcIGnAsM4t/aIAqtaFda92NAgIpA6p8N7u7KU49
# U5OzpvqP0liTFUy5LauAo6Ml+6/3CGSwekQPXBDXX2E3qk5r09JTJZ2Cc/os+XKw
# qRk5KlD6qdA8OsroW+/1X1H0+QrZlzXeaoXmIwRCrwIDAQABo4IBXzCCAVswDgYD
# VR0PAQH/BAQDAgeAMEwGA1UdIARFMEMwQQYJKwYBBAGgMgEeMDQwMgYIKwYBBQUH
# AgEWJmh0dHBzOi8vd3d3Lmdsb2JhbHNpZ24uY29tL3JlcG9zaXRvcnkvMAkGA1Ud
# EwQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwQgYDVR0fBDswOTA3oDWgM4Yx
# aHR0cDovL2NybC5nbG9iYWxzaWduLmNvbS9ncy9nc3RpbWVzdGFtcGluZ2cyLmNy
# bDBUBggrBgEFBQcBAQRIMEYwRAYIKwYBBQUHMAKGOGh0dHA6Ly9zZWN1cmUuZ2xv
# YmFsc2lnbi5jb20vY2FjZXJ0L2dzdGltZXN0YW1waW5nZzIuY3J0MB0GA1UdDgQW
# BBTUooRKOFoYf7pPMFC9ndV6h9YJ9zAfBgNVHSMEGDAWgBRG2D7/3OO+/4Pm9IWb
# sN1q1hSpwTANBgkqhkiG9w0BAQUFAAOCAQEAj6kakW0EpjcgDoOW3iPTa24fbt1k
# PWghIrX4RzZpjuGlRcckoiK3KQnMVFquxrzNY46zPVBI5bTMrs2SjZ4oixNKEaq9
# o+/Tsjb8tKFyv22XY3mMRLxwL37zvN2CU6sa9uv6HJe8tjecpBwwvKu8LUc235Ig
# A+hxxlj2dQWaNPALWVqCRDSqgOQvhPZHXZbJtsrKnbemuuRQ09Q3uLogDtDTkipb
# xFm7oW3bPM5EncE4Kq3jjb3NCXcaEL5nCgI2ZIi5sxsm7ueeYMRGqLxhM2zPTrmc
# uWrwnzf+tT1PmtNN/94gjk6Xpv2fCbxNyhh2ybBNhVDygNIdBvVYBAexGDGCBFMw
# ggRPAgEBMCowFjEUMBIGA1UEAwwLRWRlbiBOZWxzb24CEC+bSyNJAfebQtJ0Sc1e
# 7iowCQYFKw4DAhoFAKBaMBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZI
# hvcNAQkDMQwGCisGAQQBgjcCAQQwIwYJKoZIhvcNAQkEMRYEFAF0WLuf2Kq+rFJ9
# dCaVLBcbgUDOMA0GCSqGSIb3DQEBAQUABIIBAAeIA+2Axg4hBX06LzJS14es22YK
# 9x7vQuhDzD6MyzAVLlPCv57v9GsDlKVJtGz9+6kCsLtWeNnJoSUcW+Tya1DZeK2Q
# oWJeQaw062B0EDINz3M1nNFP3Y784YmojOfkD06cAV/C5lMJixrTcN2J3fEpAYnr
# 4RDqiXTm6bMylVyl6/U6bvMgukaeD+hoKJ+1re2152N8zX724P4DcPBWe4wGcAWs
# rvFI9MeTlPeJ9xfzMfRh/n4TOinsPEDsbNpXiTdV0OhCwMkEbrf11My5mDq6FSt6
# 2fh+VxLraArnLikwin7DRlTTxJx0puOHUu7P4K+3Wnpnu3TOwWGnLmja7fWhggKi
# MIICngYJKoZIhvcNAQkGMYICjzCCAosCAQEwaDBSMQswCQYDVQQGEwJCRTEZMBcG
# A1UEChMQR2xvYmFsU2lnbiBudi1zYTEoMCYGA1UEAxMfR2xvYmFsU2lnbiBUaW1l
# c3RhbXBpbmcgQ0EgLSBHMgISESHWmadklz7x+EJ+6RnMU0EUMAkGBSsOAwIaBQCg
# gf0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTcx
# MDE5MjI0NTA2WjAjBgkqhkiG9w0BCQQxFgQUcYSIqeSo2/Wt+FiSp//7d9MiFyow
# gZ0GCyqGSIb3DQEJEAIMMYGNMIGKMIGHMIGEBBRjuC+rYfWDkJaVBQsAJJxQKTPs
# eTBsMFakVDBSMQswCQYDVQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1z
# YTEoMCYGA1UEAxMfR2xvYmFsU2lnbiBUaW1lc3RhbXBpbmcgQ0EgLSBHMgISESHW
# madklz7x+EJ+6RnMU0EUMA0GCSqGSIb3DQEBAQUABIIBAG61GFBRL12SYdZkPbVb
# pnaTYPqE01vLvFJGfycyc1M+cgk7CkY/mayfIgXowMp1fzr2aji50svkZboAlpT5
# WP44WKaqmRpck5pcHTGndg079eeqZK44CgpNEvS6keHT7yGjBvC+V4iBZNHlhARV
# pb6vaWCOLl2hCD1+MieOYKM1bP/gXSMNhBzkTElfU5VdCQEmgf2fHPmzhz1rKlhm
# OSJqGAY5n7TLB3geuBdrg/TTTKkTDlb3B5boeKwwNobrd6w9oGtgv2h2gHJ4iFvr
# IRHfW2oqfEciiWolbS+UgUI45WTNlPTp8SIO9Agp6d/ULdX7Hn0/KLwvgMc/6Dp9
# ha0=
# SIG # End signature block
